DROP TRIGGER actualizarCaja

CREATE TRIGGER registrarMovimiento ON tb_movimiento_cajas 
FOR INSERT 
AS
	BEGIN
		DECLARE @IDCAJA AS CHAR(4),
				@TIPOMOV CHAR(1),
				@IMPORTE_SOL AS DECIMAL(18,2), @MONTOACT_SOL AS DECIMAL(18,2),
				@IMPORTE_DOL AS DECIMAL(18,2), @MONTOACT_DOL AS DECIMAL(18,2),
				@TOTAL_SOL AS DECIMAL(18,2), @TOTAL_DOL AS DECIMAL(18,2)
 
		--DATOS A SER INSERTADOS
		-------------------------
		SELECT @IDCAJA = CAJ_Codigo FROM INSERTED
		SELECT @TIPOMOV = MCAJ_Tipo FROM INSERTED
		SELECT @IMPORTE_SOL = MCAJ_MontoSoles FROM INSERTED
		SELECT @IMPORTE_DOL = MCAJ_MontoDolares FROM INSERTED
		
		SELECT @MONTOACT_SOL = (SELECT DCAJ_MontoActual_Soles FROM tb_detalle_cajas 
								WHERE CAJ_Codigo = @IDCAJA AND DCAJ_Estado='1')
		SELECT @MONTOACT_DOL = (SELECT DCAJ_MontoActual_Dolares FROM tb_detalle_cajas 
								WHERE CAJ_Codigo = @IDCAJA AND DCAJ_Estado='1')

		IF @TIPOMOV = 'I'
			BEGIN
				SELECT @TOTAL_SOL = (@MONTOACT_SOL + @IMPORTE_SOL)
				SELECT @TOTAL_DOL = (@MONTOACT_DOL + @IMPORTE_DOL)
			END
		ELSE IF @TIPOMOV = 'E'
			BEGIN
				SELECT @TOTAL_SOL = (@MONTOACT_SOL - @IMPORTE_SOL)
				SELECT @TOTAL_DOL = (@MONTOACT_DOL - @IMPORTE_DOL)
			END
		
		UPDATE tb_detalle_cajas
		SET DCAJ_MontoActual_Soles = @TOTAL_SOL,
			DCAJ_MontoActual_Dolares = @TOTAL_DOL
		WHERE CAJ_Codigo = @IDCAJA AND DCAJ_Estado = '1'
	END
GO